<script setup>
import { computed } from 'vue';

// ==========================================
// 👇 这里是自动生成逻辑 👇
// 因为你的图片是 1.jpg 到 15.jpg，所以我写了个循环
const photo_filenames = [];
const total_photos = 15; // 👈 如果以后加图片，只要改这个数字就行（比如改成 20）

for (let i = 1; i <= total_photos; i++) {
    photo_filenames.push(`${i}.jpg`);
    }
    // ==========================================

    // 自动加上路径前缀（适配 GitHub Pages）
    const photo_list = photo_filenames.map(name => `${import.meta.env.BASE_URL}images/${name}`);

    // 复制两份列表，实现无缝滚动效果
    const duplicated_photo_list = computed(() => {
        return [...photo_list, ...photo_list]; 
        });
        </script>

        <template>
            <div class="bg">
                    <div class="container">
                                <!-- 第一行：向左滚 -->
                                            <div class="scroll-container">
                                                            <ol class="boxes boxes-forward">
                                                                                <li class="box" v-for="(photo, i) in duplicated_photo_list" :key="'row1-'+i">
                                                                                                        <img :src="photo" loading="lazy" />
                                                                                                                            </li>
                                                                                                                                            </ol>
                                                                                                                                                        </div>
                                                                                                                                                                    
                                                                                                                                                                                <!-- 第二行：向右滚 -->
                                                                                                                                                                                            <div class="scroll-container">
                                                                                                                                                                                                            <ol class="boxes boxes-backward">
                                                                                                                                                                                                                                <li class="box" v-for="(photo, i) in duplicated_photo_list" :key="'row2-'+i">
                                                                                                                                                                                                                                                        <img :src="photo" loading="lazy" />
                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                            </ol>
                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                    <!-- 第三行：向左滚 -->
                                                                                                                                                                                                                                                                                                                                <div class="scroll-container">
                                                                                                                                                                                                                                                                                                                                                <ol class="boxes boxes-forward">
                                                                                                                                                                                                                                                                                                                                                                    <li class="box" v-for="(photo, i) in duplicated_photo_list" :key="'row3-'+i">
                                                                                                                                                                                                                                                                                                                                                                                            <img :src="photo" loading="lazy" />
                                                                                                                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                </ol>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </template>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        <style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* 全局背景黑底，防白边 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                        body { margin: 0; padding: 0; overflow-x: hidden; width: 100vw; height: 100vh; background-color: #000; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </style>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        <style scoped>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        .bg { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                            position: relative; width: 100%; min-height: 100vh; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                /* 背景颜色：你可以改这里的颜色代码 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: linear-gradient(-45deg, #ff9a9e, #fad0c4, #fad0c4, #ffdde1); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background-size: 300% 300%; animation: gradient 15s ease infinite; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: flex; justify-content: center; align-items: center; overflow: hidden;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .container { width: 100%; display: flex; flex-direction: column; justify-content: center; height: 100vh; }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @keyframes gradient { 0% { background-position: 0% 0%; } 50% { background-position: 100% 100%; } 100% { background-position: 0% 0%; } }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .scroll-container { position: relative; width: 100vw; height: 220px; margin-bottom: 20px; }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .boxes { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                position: absolute; display: flex; height: 100%; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    animation: scroll linear infinite; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        animation-duration: 60s; /* 滚动速度：数字越大越慢 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gap: 15px; padding-left: 0; align-items: center;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /* 滚动动画 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .boxes-forward { animation-name: scrollForward; left: 0; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .boxes-backward { animation-name: scrollBackward; right: 0; } /*向右滚的贴右边开始*/

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @keyframes scrollForward { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0% { transform: translateX(0); } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    100% { transform: translateX(-50%); } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @keyframes scrollBackward { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        0% { transform: translateX(0); } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            100% { transform: translateX(50%); } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /* 照片卡片样式 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .box { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                list-style: none; position: relative; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: 180px; height: 180px; flex-shrink: 0; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border-radius: 10px; transition: all 0.3s ease; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            box-shadow: 0 4px 15px rgba(0,0,0,0.3); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                opacity: 0.9; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transform: perspective(500px) rotateY(-10deg); /* 3D 倾斜效果 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .boxes-backward .box { transform: perspective(500px) rotateY(10deg); } /* 反向倾斜 */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .box img { width: 100%; height: 100%; object-fit: cover; border-radius: 10px; pointer-events: none; }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /* 鼠标/手指按住的效果 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .box:hover { opacity: 1; z-index: 10; transform: scale(1.2) rotateY(0deg); box-shadow: 0 10px 25px rgba(0,0,0,0.5); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .boxes:hover { animation-play-state: paused; } /* 摸上去暂停滚动 */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /* 手机端适配 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @media (max-width: 768px) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .scroll-container { height: 140px; margin-bottom: 10px; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .box { width: 110px; height: 110px; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .box:hover { transform: scale(1.1) rotateY(0deg); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </style>